maxconn = 32
httpchk = ""

pgsqlchk = "status_user"

[front-end]
listen = "*"
port = 80
mode = "http"

[status]
enabled = true
listen = "*"
port = 9000
user = "admin"
password = "password"
uri = "/haproxy-stats"

# [[backend.members]]
# ip = "127.0.0.1"
# port = 8080
